version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Running npm install
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - git checkout $Branch
      - git config user.email "$UserName"
      - git config user.name "$UserName"
      - cd components
      - pwd
      - bash VersionChange.sh
      - pwd
      - cd ..
      - cd examples/forms
      - pwd
      - ls
      - npm install
      - npm run build
      - echo "Build completed on `date`"
  deploy:
    commands:
      - pwd
      - echo "Deploying to $DEST_BUCKET"
      - aws s3 sync --delete build s3://$DEST_BUCKET
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
  post_deploy:
    commands:
      - git status
      - git add .
      - git commit -m "Pipeline changes"
      - git push --set-upstream origin $Branch
      - |
        if [[ ${Environment} == prod2 ]]; then
           git remote add github https://${GIT_TOKEN}@github.com/instnt-inc/instnt-android-sdk.git
           git push --force github master
        fi
      


