version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Running npm install
  build:
    commands:
      - set -e
      - echo "Starting build `date` in `pwd`"
      - git checkout $Branch
      - git config user.email "$UserName"
      - git config user.name "$UserName"
      - cd components
      - pwd
      - bash VersionChange.sh
      - pwd
      - cd ..
      - cd examples/forms
      - pwd
      - ls
      - npm install
      - npm run build
      - echo "Build completed on `date`"
  post_build:
    commands:
      - set -e
      - pwd
      - echo "Deploying to $DEST_BUCKET"
      - aws s3 sync --delete build s3://$DEST_BUCKET
      - echo "Invalidating distribution $CLOUDFRONT_DIST_ID"
      - RES=$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --path "/*")
      - INVALIDATION_ID=$(echo $RES | jq -r .Invalidation.Id)
      - echo "INVALIDATION-ID = $INVALIDATION_ID"
      - aws cloudfront wait invalidation-completed --region $REGION --distribution-id $CLOUDFRONT_DIST_ID --id $INVALIDATION_ID
      - echo "Successfully invalidated $CLOUDFRONT_DIST_ID"
      - cd ../..
      - pwd
      - git status
      - |
        if [[ ${Environment} == dev2 ]]; then
           git add .
           git commit -m "Pipeline changes"
           git push --set-upstream origin $Branch
        fi
      - |
        if [[ ${Environment} == prod2 ]]; then
           git add .
           git commit -m "Pipeline changes"
           git push --set-upstream origin $Branch
           git remote add github https://${GIT_TOKEN}@github.com/instnt-inc/instnt-react-js.git
           git push --force github master
        fi
      - echo "Pipeline Succeeded" 